#!/bin/bash
# Looks at a git commit for updated .yaml files; each updated file will have
# its monitoring information updated with omd-puppet-enc.  Meant to be used as
# a post-receive hook for a puppet ENC git repository.

tmp=$(mktemp -d /tmp/git.XXXXXX)
exit_status=0

while read oldref newref refname; do
    BRANCH=`echo $refname | sed -n 's/^refs\/heads\///p'`

    if [[ $BRANCH != 'master' ]]; then
        echo "we only look for OMD updates branch 'master'"
    else
        declare -a FILES
        FILES=$(git diff-tree --no-commit-id --name-only -r "${newref}")
        for file in ${FILES[@]}; do
            if [[ $file =~ [.]yaml$ ]]; then
                FILENAME=$tmp/`basename $file`
                git show "${newref}:${file}" > $FILENAME
                /usr/bin/omd-puppet-enc update $FILENAME
                if [[ $? -ne 0 ]]; then exit_status=2; fi
            fi
        done

        declare -a FILES_DELETE
        FILES_DELETE=$(git diff-tree --no-commit-id --diff-filter=D --name-only -r "${newref}")
        for file in ${FILES_DELETE[@]}; do
            if [[ $file =~ [.]yaml$ ]]; then
                FILENAME=$tmp/`basename $file`
                git show "${oldref}:${file}" > $FILENAME
                /usr/bin/omd-puppet-enc delete $FILENAME
                if [[ $? -ne 0 ]]; then exit_status=2; fi
            fi
        done
    fi
done

rm -rf $log $tmp $tree
exit $exit_status
